# PyTorch Basics

In this section we describe about PyTorch and tensors, Tensor Manipulations, Data Loading, and GPUs and CUDA Tensors.

## Torch Tensor

A torch.Tensor is a fundamental data structure in PyTorch, designed to represent a multi-dimensional matrix containing elements of a single data type.

Tensors are the backbone of PyTorch and are used extensively for numerical computation and neural network modeling, enabling efficient operations on GPUs.

### How to create a tensor

In [2]:
import numpy as np

In [1]:
import torch

def TorchTensor(tensorList):
    return torch.tensor(tensorList)

#### 1. Creating a Tensor from a list of values(1-dimensional)

In [7]:
## a Tensor created from a list
tensorList = [(np.sqrt(i)+ np.pi)**2 for i in range(0,4)]
Tensor = TorchTensor(tensorList)

In [14]:
print(f"The torch tensor createad is:\n{Tensor}")

The torch tensor createad is:
tensor([ 9.8696, 17.1528, 20.7554, 23.7524], dtype=torch.float64)


#### 2. Creating a Tensor from a matrix(multidimensional)

In [20]:
tensorList_1 = [(np.sqrt(i)**1+ np.pi)**2 for i in range(0,4)]
tensorList_2 = [(np.sqrt(i)**2+ np.pi)**3 for i in range(0,4)]
tensorList_3 = [(np.sqrt(i)**3+ np.pi)**4 for i in range(0,4)]
MatrixList = np.asarray([tensorList_1,tensorList_2,tensorList_3])

In [21]:
MatrixList

array([[   9.8696044 ,   17.15278971,   20.75537028,   23.75240059],
       [  31.00627668,   71.03986784,  135.92301493,  231.65571794],
       [  97.40909103,  294.21819478, 1270.29058633, 4832.75134481]])

In [22]:
MatrixTensor = TorchTensor(MatrixList)

In [23]:
print(f"The torch tensor createad is:\n{MatrixTensor}")

The torch tensor createad is:
tensor([[   9.8696,   17.1528,   20.7554,   23.7524],
        [  31.0063,   71.0399,  135.9230,  231.6557],
        [  97.4091,  294.2182, 1270.2906, 4832.7513]], dtype=torch.float64)
