# PyTorch Basics

In this section we describe about PyTorch and tensors, Tensor Manipulations, Data Loading, and GPUs and CUDA Tensors.

## Torch Tensor

A torch.Tensor is a fundamental data structure in PyTorch, designed to represent a multi-dimensional matrix containing elements of a single data type.

Tensors are the backbone of PyTorch and are used extensively for numerical computation and neural network modeling, enabling efficient operations on GPUs.

### How to create a tensor

In [1]:
import numpy as np

In [2]:
import torch

def TorchTensor(tensorList):
    return torch.tensor(tensorList)

#### 1. Creating a Tensor from a list of values(1-dimensional)

In [3]:
## a Tensor created from a list
tensorList = [(np.sqrt(i)+ np.pi)**2 for i in range(0,4)]
Tensor = TorchTensor(tensorList)

In [4]:
print(f"The torch tensor createad is:\n{Tensor}")

The torch tensor createad is:
tensor([ 9.8696, 17.1528, 20.7554, 23.7524], dtype=torch.float64)


#### 2. Creating a Tensor from a matrix(multidimensional)

In [5]:
tensorList_1 = [(np.sqrt(i)**1+ np.pi)**2 for i in range(0,4)]
tensorList_2 = [(np.sqrt(i)**2+ np.pi)**3 for i in range(0,4)]
tensorList_3 = [(np.sqrt(i)**3+ np.pi)**4 for i in range(0,4)]
MatrixList = np.asarray([tensorList_1,tensorList_2,tensorList_3])

In [6]:
MatrixList

array([[   9.8696044 ,   17.15278971,   20.75537028,   23.75240059],
       [  31.00627668,   71.03986784,  135.92301493,  231.65571794],
       [  97.40909103,  294.21819478, 1270.29058633, 4832.75134481]])

In [22]:
MatrixTensor = TorchTensor(MatrixList)

In [23]:
print(f"The torch tensor createad is:\n{MatrixTensor}")

The torch tensor createad is:
tensor([[   9.8696,   17.1528,   20.7554,   23.7524],
        [  31.0063,   71.0399,  135.9230,  231.6557],
        [  97.4091,  294.2182, 1270.2906, 4832.7513]], dtype=torch.float64)


### Creating a tensor from a uniform distribution $U([0,1))$

The continuous uniform distributions or rectangular distributions are a family of symmetric probability distributions.

#### Continuous uniform distribution

The distribution is often abbreviated $U(a,b)$ and describes an experiment where there is an arbitrary outcome that lies between $a$ and $b$, which are the minimum and maximum values.

#### Probability density function

The probability density function of the continuous uniform distribution $U(a,b)$ is

$$
f(x) = 
\begin{cases} 
\frac{1}{b-a} & \text{for } a \leq x \leq b, \\
0 & \text{for } x < a \text{ or } x > b.
\end{cases}
$$

or, in terms of mean and variance, $\mu$ and $\sigma^2$, respectivaly, is

$$
f(x) = 
\begin{cases} 
\frac{1}{2\sigma \sqrt(3)} & \text{for } -\sigma \sqrt(3) \leq x - \mu \leq \sigma \sqrt(3), \\
0 & \text{ortherwise} .
\end{cases}
$$

#### Pytorch Method

PyTorch has the `.rand()` method to generate the uniform distribution.

In [7]:
# 3x4 tensor with values from [0, 1)

random_tensor = torch.rand(3, 4)


In [31]:
print(random_tensor)

tensor([[0.1986, 0.5969, 0.6137, 0.9575],
        [0.6322, 0.1108, 0.3165, 0.1926],
        [0.9491, 0.0603, 0.7940, 0.1941]])


In [8]:
# raw x column tensor with values from [a, b)
def uniform_distribution(raw, column,a,b):
    theta = torch.rand(raw,column)
    return a*(1-theta) +b*theta

In [11]:
random_tensor_ud = uniform_distribution(raw = 3, column = 4, a = 2, b = 5)

In [12]:
random_tensor_ud

tensor([[3.4592, 4.9762, 2.5054, 2.5351],
        [2.7072, 3.8288, 2.5966, 4.9577],
        [4.1707, 3.8777, 2.8984, 2.7822]])

### Creates a tensor from a normal distribution (Gaussian distribution) 
### $G(\sigma = 0, \text{VAR} = 1)$

In [26]:
# 2x5 tensor with values from a normal distribution
normal_tensor = torch.randn(2, 5)

In [27]:
print(normal_tensor)

tensor([[-0.9998,  0.1130,  0.4859, -0.5137, -0.3902],
        [-2.5123,  0.2540, -0.5982,  1.1695,  1.2314]])
